# Generated by Django 3.2.6 on 2021-09-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=15)),
                ('institute', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
    ]
