# Generated by Django 3.2.8 on 2021-10-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=15)),
                ('Category_Description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('Institute', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('Pincode', models.CharField(max_length=6)),
                ('Website_link', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('Instrument_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Manufacturer', models.CharField(max_length=30)),
                ('Availability', models.IntegerField()),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category_description')),
                ('Institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.institute')),
            ],
        ),
        migrations.DeleteModel(
            name='Equipments',
        ),
        migrations.CreateModel(
            name='Instrument_Description',
            fields=[
                ('Instrument_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.instruments')),
                ('Instrument_Description', models.CharField(max_length=30)),
                ('Origin', models.CharField(max_length=15)),
            ],
        ),
    ]
