# Generated by Django 3.2.8 on 2021-10-18 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211019_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument_description',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrument_description',
            name='Instrument_ID',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='website.instruments'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='Instrument_ID',
            field=models.IntegerField(unique=True),
        ),
    ]
