# Generated by Django 3.2.8 on 2021-10-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211019_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruments',
            name='Institute',
        ),
    ]
