# Generated by Django 3.2.8 on 2021-11-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_instruments_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='Institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.institute'),
        ),
        migrations.AlterField(
            model_name='instrument_description',
            name='Instrument_Description',
            field=models.CharField(max_length=100),
        ),
    ]
