# Generated by Django 3.2.8 on 2021-11-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20211105_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruments',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='instruments',
            name='Institute',
        ),
        migrations.AddField(
            model_name='institute',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institute',
            name='Institute',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
