# Generated by Django 3.2.8 on 2021-11-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_institute_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_description',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instrument_description',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
