# Generated by Django 3.2.8 on 2021-11-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20211105_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='Instrument_Description',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='instruments',
            name='Origin',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='category_description',
            name='Category_Description',
            field=models.TextField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Instrument_Description',
        ),
    ]
