# Generated by Django 3.2.8 on 2021-11-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20211105_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_description',
            name='Category_Description',
            field=models.CharField(max_length=30),
        ),
    ]
