# Generated by Django 3.2.8 on 2021-11-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_category_description_category_description_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_description',
            name='Category',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
