# Generated by Django 3.2.8 on 2021-11-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_category_description_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_description',
            name='Description',
            field=models.CharField(default='', max_length=30),
        ),
    ]
