# Generated by Django 3.2.8 on 2021-11-05 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_category_description_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.category_description'),
        ),
        migrations.AddField(
            model_name='instruments',
            name='Institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.institute'),
        ),
    ]
