# Generated by Django 3.2.8 on 2021-11-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20211106_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruments',
            name='Category',
        ),
    ]
