# Generated by Django 3.2.8 on 2021-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_instruments_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_description',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
