# Generated by Django 3.2.8 on 2021-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_category_description_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_description',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
