# Generated by Django 3.2.8 on 2021-11-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_category_description_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruments',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='instruments',
            name='Institute',
        ),
    ]
